# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fffc404acc87dfbaa25460de920f885a8928adebea802a42a8b76257ec078afb1ad54d5ee41105fa8b215337a103524b75d5968bbc1ba5b6061160eb34b745a8

test:
  secret_key_base: 518b31ce0fdc5064be93f4ea801586598c3a349c35addeb872b5c6f2e204340a06693849aae59af9d3efd08af4cbca53aa53587e390cdd8080120d716b5f8fea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
